version: '3.8'

services:

  productsapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - mongodb
      - rabbitmq
    networks:
      - productapi_default

  postgres:
    container_name: product_postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: product_db
    ports:
      - "5432:5432"
    networks:
      - productapi_default

  mongodb:
    container_name: product_mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - productapi_default

  rabbitmq:
    container_name: product_rabbit
    image: rabbitmq:3-management
    ports:
      - "5672:5627"
      - "15672:15672"
    networks:
      - productapi_default

networks:
  productapi_default:
    external: true
